version: "3.7"

services:
  app:
    build: ..
    container_name: django-gunicorn
    restart: always
    env_file:
      - django.env

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - django.env

volumes:
  postgres_data:
