version: "3.7"

services:
  app:
    image: alexmikhalochkin/jarvis:latest
    expose:
      - "8000"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 jarvis.wsgi:application"

  db:
    expose:
      - "5432"

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
